### ISSUE TITLE
zombie on creating looper

### ISSUE THREAD

**Issue by harryhaaren** [mwylde/loopers#17]
Hi Micah,

Great project - love it. Looking at some Rust projects myself (previously done audio in C/C++) and found your Loopers-jack code. 

Playing around with it now - getting some "zombified" messages from JACK when adding a looper instance. Is this expected?

I have lots of experience with message-passing and C/C++ audio app design, could provide some input/design ideas for implementing "real-time-safe" looper additions, however I thought better to ask first if this is a known issue, and perhaps you've thought of a good way to solve it too??

Side note, I might try getting this ported to LV2 for use on the MOD Devices effects box; https://moddevices.com/

Great work, looking forward to messing with it a bit more. -Harry

**Comment by mwylde** [comment]
Thanks for taking a look! Can you try again with the latest master? Before 306c03660494ffd522e37c267470432437dc1ab5, jack ports were incorrectly being registered on the audio thread when a new looper was created.

**Comment by harryhaaren** [comment]
Hi Micah!

Just re-tested and its working fine now. Strange thing is, I didn't even rebuild Loopers! (I had previously tested git-master already). I had only just re-installed the OS here, and setup JACK stuff, so with a reboot inbetween perhaps there were some RT permission issues with getting Jackd working... so apologies for the noise here, I can't reproduce this, so will mark as closed.

Haven't got to using Loopers yet with real instruments, but will provide feedback when I have. Regards, -Harry
