### ISSUE TITLE
GUI does not scale for high pixel density screens

### ISSUE THREAD

**Issue by Be-ing** [mwylde/loopers#2]
![image](https://user-images.githubusercontent.com/9455094/101058288-99de3880-3552-11eb-8c00-fc190d61a096.png)

**Comment by mwylde** [comment]
Thanks for the report! I don't have a hidpi display to test with, but I think I've made the necessary fixes in #3. Do you mind testing that out and let me know if it fixes things for you?

**Comment by mwylde** [comment]
Fixed by #3
